name: Docker Build Test Publish

on:
  push:
    branches:
      - main
      - seed
    tags:
      - v*
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openeo_insar # ${{ github.repository }}

jobs:
  build-and-publish-job:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: read
      packages: write
    outputs:
      TIME_TAG: ${{ steps.time-tag-step.outputs.TIME_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        # TODO: Build with cache?
        run: |
          set -euxo pipefail
          docker build . -f OpenEO_Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        id: time-tag-step
        # Assume that this job takes more than a minute to run. Then concurrency will ensure a unique TIME_TAG.
        # The docker build takes 3 minutes, so this should be safe.
        run: |
          set -euxo pipefail
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          TIME_TAG=$(date +'%Y%m%dT%H%M')
          echo "TIME_TAG=$TIME_TAG" >> $GITHUB_OUTPUT
          docker tag $IMAGE_NAME $IMAGE_ID:$TIME_TAG
          docker push $IMAGE_ID:$TIME_TAG

  test-job:
    runs-on: ubuntu-latest
    needs: build-and-publish-job
    permissions:
      contents: read
      packages: write
    env:
      TIME_TAG: ${{ needs.build-and-publish-job.outputs.TIME_TAG }}
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run run_pytest.sh
        run: |
          set -euxo pipefail
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker run --rm \
            -v $(pwd):/src \
            -w /src \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            $IMAGE_ID:$TIME_TAG run_pytest.sh
