name: Docker Build Test Publish

on:
  push:
    branches:
      - main
      - seed
    tags:
      - v*
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openeo_insar # ${{ github.repository }}

jobs:
  current-datetime:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build . -f OpenEO_Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Set current date as env variable
        # Assume that this job takes more than a minute to run. Then concurrency will ensure a unique TIME_TAG.
        # The docker build takes 3 minutes, so this should be safe.
        run: echo "TIME_TAG=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
#      - name: Run run_pytest.sh
#        run: |
#          docker run --rm \
#            -v $(pwd):/src \
#            -w /src \
#            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
#            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
#            openeo_insar run_pytest.sh

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$TIME_TAG

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
